version: "3.2"
services:
    app:
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        container_name: app
        restart: unless-stopped
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        volumes:
            - '.:/var/www/html'
        networks:
            - app-network
    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        tty: true
        ports:
            - "9500:80"
        links:
            - app
        volumes:
            - ./:/var/www/html/
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d
        networks:
            - app-network
    mysql:
        image: mysql:5.7.32
        container_name: db
        restart: unless-stopped
        tty: true
        ports:
            - "13012:3306"
        volumes:
            - mysql_data_php:/var/lib/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
        environment:
            MYSQL_DATABASE: laravel_web
            MYSQL_ROOT_PASSWORD: password
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - app-network
    redis:
        image: 'redis:alpine'
        container_name: redis
        ports:
            - "6379:6379"
        volumes:
            - redis_data_php:/data
        networks:
            - app-network
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            retries: 3
            timeout: 5s
networks:
    app-network:
        driver: bridge
volumes:
    mysql_data_php:
        driver: local
    redis_data_php:
        driver: local
